[project]
name = "tecroom"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "recommonmark>=0.7.1",
]

[[tool.uv.index]]
url="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
