name: release
on:
  push:
    branches:
      - master
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}  # 确保检出当前分支或 tag
      - name: Changelog
        uses: googleapis/release-please-action@v4.3
        id: release
        with:
            token: ${{ secrets.RELEASE_TOKEN }}
            from-tag: v2.0.0
            to-tag: HEAD

     