name: release
on:
  push:
    branches:
      - master
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        with:
            token: ${{ secrets.RELEASE_TOKEN }}
            from-tag: v2.0.0
            to-tag: HEAD
            release-type: simple

     